### ISSUE TITLE
Create Dev branch in PhyloNetworks

### ISSUE THREAD

**Issue by jjustison** [JuliaPhylo/PhyloNetworks.jl#214]
1. Create Dev branch in PhyloNetworks
2. Take out functions and tests from the Dev branch to create new packages
3. Run test locally
4. Everyone should work from the dev branch

**Comment by jjustison** [comment]
I Made a branch labeled `development`. 

To keep in line with the spirit of item **4.**, we can protect the main and require pull requests or approval to change it. I can do this if of interest.

**Comment by crsl4** [comment]
Josh, we wanted the recent PR on urls to be in the development branch (which is why we hadn't created it). Let's just make sure the development branch has the latest commits on url changes.

**Comment by crsl4** [comment]
Regarding the protection of main, we already added that, thanks!

**Comment by crsl4** [comment]
Josh, we created a new branch called `dev` after merging the PR on urls to master.
